version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: "picovico-artifacts-1756198500.37837"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install build tools"
      - pip install --upgrade pip
      # Install AWS SAM CLI (latest stable)
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Pre-build: show versions"
      - python --version
      - aws --version
      - sam --version
      - echo "Using ARTIFACT_BUCKET=$ARTIFACT_BUCKET"
  build:
    commands:
      - echo "Running SAM build"
      - sam build
      - |
        echo "Packaging SAM template"
        sam package --s3-bucket "$ARTIFACT_BUCKET" --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "Build completed"
      - ls -la

artifacts:
  files:
    - packaged.yaml
    - .aws-sam/**/*
  discard-paths: yes

cache:
  paths:
    - /root/.cache/pip/**/*
    - ~/.cache/pip/**/*
